server:
  port: 9000

eureka:
  client:
    register-with-eureka: true #유레카 디스커버리 서버의 등록 여부
    fetch-registry: true #defalutZone의 유레카 서버에서 클라이언트 정보를 가져오는 것의 여부
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service #유레카 서버에 등록되는 서비스 명
  cloud:
    gateway:
      routes: #응답을 보낼 목적지 URL, 필터 항목을 식별하기 위한 ID로 구성
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: #요청을 처리하기전 HTTP 요청이 정의된 조건에 부합하는지 검사
            - Path=/user-service/**